MAKEFILE_DIR := $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))

RUN_TAG = $(shell ls librelane/runs/ | tail -n 1)
TOP = chip_top

PDK_ROOT ?= $(MAKEFILE_DIR)/gf180mcu
PDK ?= gf180mcuD
PDK_COMMIT ?= f6eeac7dad085ffcc829ccfd721f7b4ce39edcf7

# Available SCL libraries:
# gf180mcu_as_sc_mcu7t3v3
# gf180mcu_fd_sc_mcu7t5v0
# gf180mcu_fd_sc_mcu9t5v0
# gf180mcu_osu_sc_gp9t3v3 (broken)
# gf180mcu_osu_sc_gp12t3v3 (broken)

ifeq ($(SCL),default)
    SCL = gf180mcu_fd_sc_mcu7t5v0
endif
SCL ?= gf180mcu_fd_sc_mcu7t5v0

# Available PAD libraries:
# gf180mcu_fd_io
# gf180mcu_ocd_io

ifeq ($(PAD),default)
    PAD = gf180mcu_fd_io
endif
PAD ?= gf180mcu_fd_io

# Available SRAM macros:
# gf180mcu_fd_ip_sram
# gf180mcu_ocd_ip_sram

ifeq ($(SRAM),default)
    SRAM = gf180mcu_fd_ip_sram
endif
SRAM ?= gf180mcu_fd_ip_sram

ifeq ($(SRAM),gf180mcu_fd_ip_sram)
    MACROS = 5v
else
    MACROS = 3v3
endif

AVAILABLE_SLOTS = 1x1 0p5x1 1x0p5 0p5x0p5
DEFAULT_SLOT = 1x1

# Standalone final-GDS flow.  This deliberately does not use the padring
# generated by this repository: FINAL_GDS_SOURCE is imported directly, the
# narrowly validated GF180 DRC repairs are applied, and only the Wafer.Space
# GF180 seal ring is merged around it.
FINAL_GDS_SOURCE ?= $(MAKEFILE_DIR)/../gds/padring_test_structures.gds
FINAL_GDS_TOP ?= chip_top
FINAL_GDS_SLOT ?= 1x0p5
FINAL_DIE_WIDTH = $(if $(filter 1x1 1x0p5,$(FINAL_GDS_SLOT)),3932,1936)
FINAL_DIE_HEIGHT = $(if $(filter 1x1 0p5x1,$(FINAL_GDS_SLOT)),5122,2531)
FINAL_DIR ?= $(MAKEFILE_DIR)/final
SIGNOFF_DIR ?= $(MAKEFILE_DIR)/.signoff
PRECHECK_RUN_DIR ?= $(SIGNOFF_DIR)/precheck-run
KLAYOUT_DRC_VARIANT ?= D
KLAYOUT_DRC_RUN_MODE ?= deep
KLAYOUT_DRC_THREADS ?= 1
KLAYOUT_DRC_RUN_TAG ?= RUN_$(shell date -u +%Y-%m-%d_%H-%M-%S)
KLAYOUT_DRC_RUN_DIR ?= $(SIGNOFF_DIR)/klayout-drc-runs/$(KLAYOUT_DRC_RUN_TAG)
KLAYOUT_DRC_INPUT ?= $(FINAL_DIR)/$(FINAL_GDS_TOP).gds
WS_PDK_REPO ?= https://github.com/wafer-space/gf180mcu.git
WS_PDK_COMMIT ?= ac7d8696de96a4d708e768b607ae37f02207a354
WS_PRECHECK_REPO ?= https://github.com/wafer-space/gf180mcu-precheck.git
WS_PRECHECK_COMMIT ?= 59207bbebaf2f5e5bb5f3e9441199a71948b1fdc

# Slot can be any of AVAILABLE_SLOTS
SLOT ?= $(DEFAULT_SLOT)

ifeq ($(SLOT),default)
    SLOT = $(DEFAULT_SLOT)
endif

ifeq ($(filter $(SLOT),$(AVAILABLE_SLOTS)),)
    $(error $(SLOT) does not exist in AVAILABLE_SLOTS: $(AVAILABLE_SLOTS))
endif

SLOT_DEFINE = SLOT_$(shell echo $(SLOT) | tr '[:lower:]' '[:upper:]')
SRAM_DEFINE = SRAM_$(SRAM)

LIBRELANE_OPTS = --pdk ${PDK} --pdk-root ${PDK_ROOT} --manual-pdk --scl ${SCL} --pad ${PAD}
LIBRELANE_CONFIGS = librelane/slots/slot_${SLOT}.yaml librelane/macros/macros_${MACROS}.yaml librelane/config.yaml

.DEFAULT_GOAL := help

help: ## Show this help message
	@echo 'Usage: make [target]'
	@echo ''
	@echo 'Available targets:'
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  %-20s %s\n", $$1, $$2}'
.PHONY: help

all: librelane ## Build the project (runs LibreLane)
.PHONY: all

$(PDK_ROOT)/ciel/gf180mcu/versions/$(PDK_COMMIT)/$(PDK):
	ciel enable $(PDK_COMMIT) --pdk-root $(PDK_ROOT) --pdk-family $(PDK) --include-libraries all

clone-pdk: $(PDK_ROOT)/ciel/gf180mcu/versions/$(PDK_COMMIT)/$(PDK) ## Clone the gf180mcu PDK
.PHONY: clone-pdk

# Need to find a better way to
# pass the variables to LibreLane
defines:
	@echo "Writing src/generated_defines.svh"
	$(file >src/generated_defines.svh,// This file is auto-generated by the Makefile)
	$(file >>src/generated_defines.svh,`define ${SLOT_DEFINE})
	$(file >>src/generated_defines.svh,`define ${SRAM_DEFINE})
.PHONY: defines

librelane: clone-pdk defines ## Run LibreLane flow (synthesis, PnR, verification)
	SRAM_DEFINE=${SRAM_DEFINE} librelane ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS} --save-views-to $(MAKEFILE_DIR)/final
.PHONY: librelane

librelane-condensed: clone-pdk defines ## Run LibreLane flow (synthesis, PnR, verification)
	SRAM_DEFINE=${SRAM_DEFINE} librelane --condensed ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS} --save-views-to $(MAKEFILE_DIR)/final
.PHONY: librelane-condensed

librelane-nodrc: clone-pdk defines ## Run LibreLane flow without DRC checks
	SRAM_DEFINE=${SRAM_DEFINE} librelane ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS} --save-views-to $(MAKEFILE_DIR)/final --skip KLayout.Antenna --skip KLayout.DRC --skip Magic.DRC
.PHONY: librelane-nodrc

librelane-klayoutdrc: clone-pdk defines ## Run LibreLane flow without magic DRC checks
	SRAM_DEFINE=${SRAM_DEFINE} librelane ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS} --save-views-to $(MAKEFILE_DIR)/final --skip Magic.DRC
.PHONY: librelane-klayoutdrc

librelane-magicdrc: clone-pdk defines ## Run LibreLane flow without KLayout DRC checks
	SRAM_DEFINE=${SRAM_DEFINE} librelane ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS} --save-views-to $(MAKEFILE_DIR)/final --skip KLayout.DRC
.PHONY: librelane-magicdrc

librelane-openroad: clone-pdk defines ## Open the last run in OpenROAD
	SRAM_DEFINE=${SRAM_DEFINE} librelane ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS} --last-run --flow OpenInOpenROAD
.PHONY: librelane-openroad

librelane-klayout: clone-pdk defines ## Open the last run in KLayout
	SRAM_DEFINE=${SRAM_DEFINE} librelane ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS} --last-run --flow OpenInKLayout
.PHONY: librelane-klayout

librelane-padring: clone-pdk defines ## Only create the padring
	python3 scripts/padring.py ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS}
.PHONY: librelane-padring

check-nix-signoff-tools: ## Refuse host tools for final-GDS and sign-off work
	python3 scripts/signoff_env.py \
		--tool python3 --tool git --tool klayout
.PHONY: check-nix-signoff-tools

$(SIGNOFF_DIR)/pdk/.git: | check-nix-signoff-tools
	mkdir -p $(SIGNOFF_DIR)
	git clone $(WS_PDK_REPO) $(SIGNOFF_DIR)/pdk
	git -C $(SIGNOFF_DIR)/pdk checkout --detach $(WS_PDK_COMMIT)

$(SIGNOFF_DIR)/precheck/.git: | check-nix-signoff-tools
	mkdir -p $(SIGNOFF_DIR)
	git clone $(WS_PRECHECK_REPO) $(SIGNOFF_DIR)/precheck
	git -C $(SIGNOFF_DIR)/precheck checkout --detach $(WS_PRECHECK_COMMIT)

check-final-gds-env: check-nix-signoff-tools $(SIGNOFF_DIR)/pdk/.git ## Require pinned Nix tools for final-GDS generation
	python3 scripts/signoff_env.py \
		--dependency $(SIGNOFF_DIR)/pdk $(WS_PDK_COMMIT)
.PHONY: check-final-gds-env

check-signoff-env: check-nix-signoff-tools $(SIGNOFF_DIR)/pdk/.git $(SIGNOFF_DIR)/precheck/.git ## Require pinned Nix tools and dependencies for sign-off
	python3 scripts/signoff_env.py \
		--tool magic \
		--dependency $(SIGNOFF_DIR)/pdk $(WS_PDK_COMMIT) \
		--dependency $(SIGNOFF_DIR)/precheck $(WS_PRECHECK_COMMIT)
.PHONY: check-signoff-env

final-gds: check-final-gds-env ## Apply validated GF180 DRC repairs and add only the GF180 seal ring
	python3 scripts/final_gds.py prepare \
		--input $(FINAL_GDS_SOURCE) \
		--output $(SIGNOFF_DIR)/prepared.gds \
		--top $(FINAL_GDS_TOP) \
		--slot $(FINAL_GDS_SLOT)
	PDK_ROOT=$(SIGNOFF_DIR)/pdk PDK=gf180mcuD python3 \
		$(SIGNOFF_DIR)/pdk/gf180mcuD/libs.tech/klayout/tech/scripts/sealring.py \
		--input $(SIGNOFF_DIR)/prepared.gds \
		--output $(SIGNOFF_DIR)/sealed.gds \
		--die-width $(FINAL_DIE_WIDTH) --die-height $(FINAL_DIE_HEIGHT)
	python3 scripts/final_gds.py finish \
		--source $(SIGNOFF_DIR)/prepared.gds \
		--sealed $(SIGNOFF_DIR)/sealed.gds \
		--output $(FINAL_DIR)/$(FINAL_GDS_TOP).gds \
		--manifest $(FINAL_DIR)/manifest.json \
		--top $(FINAL_GDS_TOP) \
		--slot $(FINAL_GDS_SLOT) \
		--source-original $(FINAL_GDS_SOURCE) \
		--pdk-commit $(WS_PDK_COMMIT)
.PHONY: final-gds

klayout-drc-final: check-signoff-env ## Run the pinned PDK's complete KLayout main DRC on KLAYOUT_DRC_INPUT
	python3 scripts/klayout_drc.py \
		--input $(KLAYOUT_DRC_INPUT) \
		--top $(FINAL_GDS_TOP) \
		--pdk-root $(SIGNOFF_DIR)/pdk \
		--pdk-commit $(WS_PDK_COMMIT) \
		--run-dir $(KLAYOUT_DRC_RUN_DIR) \
		--variant $(KLAYOUT_DRC_VARIANT) \
		--run-mode $(KLAYOUT_DRC_RUN_MODE) \
		--threads $(KLAYOUT_DRC_THREADS)
.PHONY: klayout-drc-final

signoff-final: final-gds check-signoff-env ## Run Wafer.Space precheck plus the pinned PDK's complete KLayout DRC
	mkdir -p $(PRECHECK_RUN_DIR)
	@rm -f $(SIGNOFF_DIR)/precheck-output.gds; \
	precheck_status=0; klayout_status=0; \
	PDK_ROOT=$(SIGNOFF_DIR)/pdk PDK=gf180mcuD python3 \
		$(SIGNOFF_DIR)/precheck/precheck.py \
		--input $(FINAL_DIR)/$(FINAL_GDS_TOP).gds \
		--top $(FINAL_GDS_TOP) --slot $(FINAL_GDS_SLOT) \
		--workers max --threads 1 \
		--dir $(PRECHECK_RUN_DIR) \
		--output $(SIGNOFF_DIR)/precheck-output.gds \
		--skip KLayout.DRC Checker.KLayoutDRC || precheck_status=$$?; \
	if [ -f $(SIGNOFF_DIR)/precheck-output.gds ]; then \
		python3 scripts/klayout_drc.py \
			--input $(SIGNOFF_DIR)/precheck-output.gds \
			--top $(FINAL_GDS_TOP) \
			--pdk-root $(SIGNOFF_DIR)/pdk \
			--pdk-commit $(WS_PDK_COMMIT) \
			--run-dir $(KLAYOUT_DRC_RUN_DIR) \
			--variant $(KLAYOUT_DRC_VARIANT) \
			--run-mode $(KLAYOUT_DRC_RUN_MODE) \
			--threads $(KLAYOUT_DRC_THREADS) || klayout_status=$$?; \
	else \
		echo "precheck did not produce $(SIGNOFF_DIR)/precheck-output.gds"; \
		klayout_status=2; \
	fi; \
	echo "Wafer.Space precheck status: $$precheck_status"; \
	echo "authoritative KLayout DRC status: $$klayout_status"; \
	if [ $$precheck_status -ne 0 ] || [ $$klayout_status -ne 0 ]; then exit 2; fi
.PHONY: signoff-final

sim: clone-pdk defines ## Run RTL simulation with cocotb
	cd cocotb; PDK_ROOT=${PDK_ROOT} PDK=${PDK} SLOT=${SLOT} PAD=${PAD} SCL=${SCL} SRAM=${SRAM} python3 chip_top_tb.py
.PHONY: sim

sim-gl: clone-pdk defines ## Run gate-level simulation with cocotb (after copy-final)
	cd cocotb; GL=1 PDK_ROOT=${PDK_ROOT} PDK=${PDK} SLOT=${SLOT} PAD=${PAD} SCL=${SCL} SRAM=${SRAM} python3 chip_top_tb.py
.PHONY: sim-gl

sim-view: ## View simulation waveforms in GTKWave
	gtkwave cocotb/sim_build/chip_top.fst
.PHONY: sim-view
